# utils.py
import os

def save_to_file(username, content):
    os.makedirs("output", exist_ok=True)
    with open(f"output/{username}_persona.txt", "w", encoding="utf-8") as f:
        f.write(content)
    print(f"📄 Text file saved to: output/{username}_persona.txt")

def save_persona_as_html(username, persona_text):
    html_template = f"""
    <html>
    <head>
        <title>User Persona - {username}</title>
        <style>
            body {{
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                background: #f4f4f4;
                padding: 40px;
                color: #333;
            }}
            .persona-box {{
                max-width: 900px;
                margin: auto;
                background: #fff;
                padding: 30px 40px;
                border-radius: 12px;
                box-shadow: 0 8px 20px rgba(0,0,0,0.08);
            }}
            h1 {{
                text-align: center;
                color: #222;
                font-size: 32px;
            }}
            h2 {{
                font-size: 22px;
                margin-top: 30px;
                border-bottom: 2px solid #eee;
                padding-bottom: 8px;
                color: #444;
            }}
            p {{
                font-size: 16px;
                line-height: 1.6;
                margin: 10px 0;
            }}
            blockquote {{
                font-style: italic;
                color: #666;
                border-left: 4px solid #ccc;
                margin: 20px 0;
                padding-left: 16px;
                background: #f9f9f9;
            }}
            .footer {{
                margin-top: 40px;
                text-align: center;
                font-size: 14px;
                color: #aaa;
            }}
        </style>
    </head>
    <body>
        <div class="persona-box">
            <h1>User Persona: Capital_Squirrel_545</h1>
            <div>
                {"<br>".join(persona_text.splitlines())}
            </div>
            <div class="footer">Generated by Reddit Persona Analyzer</div>
        </div>
    </body>
    </html>
    """
    os.makedirs("output", exist_ok=True)
    output_path = f"output/{username}_persona.html"
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html_template)
    print(f"🌐 HTML persona saved to: {output_path}")
